env:
  CIRRUS_CLONE_DEPTH: "20"
  # Use bash (instead of sh on linux or cmd.exe on Windows)
  CIRRUS_SHELL: bash

container:
  image: public.ecr.aws/docker/library/maven:3.9.9-amazoncorretto-23-alpine
  cpu: 2
  memory: 2G

build_task:
  build_script:
    - echo "sonar-dummy-maven"
