aws_credentials:
  role_arn: arn:aws:iam::275878209202:role/CirrusCI
  role_session_name: cirrus
  region: eu-central-1


artifactory_build: &artifactory_build
  ARTIFACTORY_API_KEY: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]

artifactory_private: &artifactory_private
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]

env:
  CIRRUS_CLONE_DEPTH: "20"
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  # Possible values for ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa, sonarsource-public-qa
  ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa
  # access license key
  # Use bash (instead of sh on linux or cmd.exe on Windows)
  CIRRUS_SHELL: bash

eks_container: &CONTAINER_DEFINITION
  image: 275878209202.dkr.ecr.eu-central-1.amazonaws.com/base:j11-latest
  cluster_name: CirrusCI
  region: eu-central-1
  namespace: default

ec2_instance: &INSTANCE_DEFINITION
  experimental: true # see https://github.com/cirruslabs/cirrus-ci-docs/issues/1051
  region: eu-central-1
  subnet_id: subnet-063c427f490da35b9
  type: t2.xlarge
  image: lt-base-windows-jdk17-v*
  platform: windows


only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: >
    $CIRRUS_USER_COLLABORATOR == 'true' &&
    $CIRRUS_TAG == "" &&
    ($CIRRUS_PR != "" ||
    $CIRRUS_BRANCH == 'master'
    || $CIRRUS_BRANCH =~ "branch-.*"
    || $CIRRUS_BRANCH =~ "dogfood-on-.*"
    || $CIRRUS_BUILD_SOURCE == 'api'
    )

build_task:
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  env:
    <<: [ *artifactory_build, *artifactory_private ]
    GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]
    # analysis on next
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SIGN_KEY: VAULT[development/kv/data/sign data.key]
    PGP_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
    # allow deployment of pull request artifacts to repox
    DEPLOY_PULL_REQUEST: "true"
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  build_script:
    - source cirrus-env BUILD-PRIVATE
    - regular_mvn_build_deploy_analyze
  cleanup_before_cache_script: cleanup_maven_repository

build_win_task:
  <<: *ONLY_SONARSOURCE_QA
  ec2_instance:
    <<: *INSTANCE_DEFINITION
  env:
    <<: [ *artifactory_build, *artifactory_private ]
  build_script:
    - source cirrus-env CI-PRIVATE
    - mvn.cmd test
  cleanup_before_cache_script: cleanup_maven_repository

promote_task:
  depends_on:
    - build
    - build_win
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 1
    memory: 1G
  env:
    <<: *artifactory_private
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
    # promotion cloud function
    GCF_ACCESS_TOKEN: VAULT[development/kv/data/promote data.token]
    PROMOTE_URL: VAULT[development/kv/data/promote data.url]
    # artifacts that will have downloadable links in burgr
    ARTIFACTS: com.sonarsource.dummy:sonar-dummy-plugin:jar
    BURGR_URL: VAULT[development/kv/data/burgr data.url]
    BURGR_USERNAME: VAULT[development/kv/data/burgr data.cirrus_username]
    BURGR_PASSWORD: VAULT[development/kv/data/burgr data.cirrus_password]
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  script:
    - cirrus_promote_maven
  cleanup_before_cache_script: cleanup_maven_repository
