gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]

env:
  ARTIFACTORY_URL: ENCRYPTED[4c9bce2f9fb6698533e62bb7e05bf3d33c48697cb56381c8314ed2e206232c9f2dba4f907a1715d839c49c4e8b9b7bff]
  ARTIFACTORY_PRIVATE_USERNAME: private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: ENCRYPTED[f8b5de998dff2b3a14bddc6fd317c369e72bc95fb1d3a9174d7b84fbbb787b6dfd17f1febc5385086855794bc19e5bfa]
  ARTIFACTORY_DEPLOY_USERNAME: private-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: ENCRYPTED[8ca6672031def4745329c0d849f522f3b11b4b63ccd62bdbc1e7f4e01e17bafc421841dd24788656f7bfc2984633a702]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa
  ARTIFACTORY_API_KEY: ENCRYPTED[5c3294761cf34384e9f8d605f44b2e1289f92eb89b1c2aa95c543160e519fea5d3fc977d23da93413a89fe71bafe5dce]
  # analysis on next
  SONAR_TOKEN: ENCRYPTED[8944e2060a64df95eebe87b9b19d562d74645fb3a788b3db944cc39cbff974e7a52f247b2881f60be127d635b9c3638e]
  SONAR_HOST_URL: ENCRYPTED[ffd6c6477bc98dc08be5f1fae062bc26720a7ea0940dd36f8ed5097362c0a312f54155209a7bca5f7870dc0f08a40475]
  # complete authorization header to obtain build ids from Cirrus
  #CURL_BUILD_NUMBER_AUTH: ENCRYPTED[046e8806d695796956456217d1613f0717a11ad2ccd25480e3c365ed7ba3b390a5fa1e8dfc494e800d40be9e1141f2d8]
  # tell artifact urls to burgr
  #BURGR_URL: ENCRYPTED[eaf4acbde407362180a6bdf4a8d3bd30cae96c0acfa8b617c999fc6f7e502776241c7b98e80354bace4b1e0fe65f2a7a]
  #BURGR_USERNAME: ENCRYPTED[af365756ca7265f67e4d1999f5cf2d7f2249aadb47fc5a71e1ad657e0ef0e20f900e27681707b1f8a8ccdcc3104a2f68]
  #BURGR_PASSWORD: ENCRYPTED[218cb20174dcd17109819426fa1132be3106d73d06ccd90cf230b0b0f253d3678dd21497f4b9ccace5b9faf6f8e41bf5]

linux_task:
  gke_container:
    dockerfile: Dockerfile
    builder_image_project: language-team
    builder_image_name: docker-build-lt-v1
    cluster_name: cirrus-ci-lt-cluster
    zone: us-central1-a
    namespace: default
    cpu: 2
    memory: 2G
  build_script:
    - . ./cirrus/cirrus-env.sh BUILD
    - echo $BUILD_NUMBER
    - python3 setBuildVersion.py
    - mvn deploy sonar:sonar -Pcoverage,deploy-sonarsource,release -Dmaven.test.redirectTestOutputToFile=false -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -B -e -V $*

promote_task:
  depends_on:
    - linux
  gke_container:
    dockerfile: Dockerfile
    builder_image_project: language-team
    builder_image_name: docker-build-lt-v1
    cluster_name: cirrus-ci-lt-cluster
    zone: us-central1-a
    namespace: default
    cpu: 1
    memory: 1G
  script:
    - . ./cirrus/cirrus-env.sh PROMOTE
    - curl -s "https://us-central1-cix-94919.cloudfunctions.net/promote?PROJECT=$PROJECT&PULL_REQUEST=$PULL_REQUEST&GITHUB_BRANCH=$GITHUB_BRANCH&BUILD_NUMBER=$BUILD_NUMBER"