artifactory_build: &artifactory_build
  ARTIFACTORY_API_KEY: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer username]
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]

artifactory_private: &artifactory_private
  ARTIFACTORY_PRIVATE_USERNAME: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader username]
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]

env:
  CIRRUS_CLONE_DEPTH: "20"
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  # Possible values for ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa, sonarsource-public-qa
  ARTIFACTORY_DEPLOY_REPO: sonarsource-private-qa
  # Use bash (instead of sh on linux or cmd.exe on Windows)
  CIRRUS_SHELL: bash

eks_container_definition: &CONTAINER_DEFINITION
  image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j19-latest
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default

ec2_instance_definition: &INSTANCE_DEFINITION
  region: eu-central-1
  type: t3.medium
  image: base-windows-jdk17-v*
  platform: windows

build_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  env:
    <<: [*artifactory_build, *artifactory_private]
    GITHUB_TOKEN: VAULT[development/github/token/licenses-ro token]
    # analysis on next
    SONAR_HOST_URL: VAULT[development/kv/data/next data.url]
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SIGN_KEY: VAULT[development/kv/data/sign data.key]
    PGP_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
    # allow deployment of pull request artifacts to repox
    DEPLOY_PULL_REQUEST: "true"
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  build_script:
    - source cirrus-env BUILD-PRIVATE
    - regular_mvn_build_deploy_analyze
  cleanup_before_cache_script: cleanup_maven_repository

docker_build_task:
  eks_container:
    <<: *CONTAINER_DEFINITION
    builder_role: cirrus-builder
    builder_image: docker-builder-v*
    builder_instance_type: t2.small
    dockerfile: Dockerfile
    docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  test_script:
    - node --version
    - sleep 10

build_win_task:
  ec2_instance:
    <<: *INSTANCE_DEFINITION
  env:
    <<: [*artifactory_build, *artifactory_private]
  build_script:
    - source cirrus-env CI-PRIVATE
    - mvn.cmd test
  cleanup_before_cache_script: cleanup_maven_repository

promote_task:
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && (
    $CIRRUS_PR != "" ||
    $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ||
    $CIRRUS_BRANCH =~ "gh-readonly-queue/.*" ||
    $CIRRUS_BRANCH =~ "branch-.*" ||
    $CIRRUS_BRANCH =~ "dogfood-on-.*"
    )
  depends_on:
    - build
    - build_win
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 1
    memory: 1G
  env:
    <<: *artifactory_private
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promotion token]
    ARTIFACTORY_PROMOTE_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-promoter access_token]
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  script: cirrus_promote_maven
  cleanup_before_cache_script: cleanup_maven_repository

update_stable_branch_task:
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH
  depends_on:
    - build
    - build_win
    - docker_build
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 1
    memory: 1G
  env:
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-stable token]
  script: |
    git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/$CIRRUS_REPO_FULL_NAME.git"
    git fetch origin stable:stable
    git checkout stable
    git reset --hard origin/$CIRRUS_DEFAULT_BRANCH
    git push origin stable
