aws_credentials:
  role_arn: arn:aws:iam::275878209202:role/CirrusCI
  role_session_name: cirrus
  region: eu-central-1

eks_container: &CONTAINER_DEFINITION_J11
  image: 275878209202.dkr.ecr.eu-central-1.amazonaws.com/base:j11-latest
  cluster_name: CirrusCI
  region: eu-central-1
  namespace: default

ec2_instance: &INSTANCE_DEFINITION_WIN_J17
  experimental: true # see https://github.com/cirruslabs/cirrus-ci-docs/issues/1051
  region: eu-central-1
  subnet_id: subnet-063c427f490da35b9
  type: t2.xlarge
  image: lt-base-windows-jdk17-v*
  platform: windows
