language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script: ./travis.sh

env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/jvm'

notifications:  
  email: false
  webhooks:
    urls:
      - secure: "Z+kQRaMkYW0OqDCfZPpx/JwJIqJw1ZkbfKLgr6a4bzwjypTQ/UmrLk1LdugMoQmNMnXmkVUXujLvcXoCUZb+jJ4HxG72VgUybJs8Ee94lhIuj9UT5c41SUX83mI3SIYH6kz1B2El3JUJRpeC7M52XA2g7S5QSUamOPT+pI/PVuM="
      - secure: "Oh/FF8ETpAlHijj1ENxStDSMebZN+DuvfKqFUyzLuujGV/KPni4jEsKTyiKl9GMajdNHQu6z8MSkWcDXOy2vu85CvYY0vDBLEu46Sc7E2JIZiOWKdAsiGCuurhPTgL7/gerrb0LASBMG1SflPuHitwhtZzdHw43CJAQ1UNBOM6E="
    on_start: always

