language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script: ./travis.sh

env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "t6P1sMEGgo5wlBYH34D5yPmsn/d5rgVAbQlkTkC7UUwaGVd4TfYJAHZ1d3iqaxRZeAbwr1EDYQGKi29UWttlienLeX0alc5oUXOP9CAqqr/n2TmwOhVpnLdCP9mIu6vldZlQbsvVqr0OtsEA8rHZG/U/NFTdqas5n7PwUgKkpzxDZ2OLOHtCeJcSwcWRsEG2/Vwmu9+gkTBOer+Rs04hA5EpFGTMqE9B6/OHKr57ofg4oKcZ8qU6VWdvNEuwtrI/iX5QvfNJaJnRUVmbAxc4fVsfWnK0ha5kemhmJFX05vRZXzm66x/RcUEJ+DTDSlJeKNUFg2jkGNJe9zASzC9HjxqGsRYiVWXhEgNx6Qaig2I4A3MHhQr5QPkR7kjtF7cL9UyQl3qvSlCH/hjH3egIQkQSCwJX8sv/BMZGTta46rE3H5hEM4OtwP8haSVXkpvxqaCj1l0OKcvCwDQQE5+2AYCjFIrLZ7KGr6BhJUOaxztwbBYo8tky40DGTajYVY4DJLi3g/xt1EGcF8lkODt36KGvrPaDs/fctrG7SMbOc9bOdDCZT9fCq8rVecQMk2eOfORibWqs9lZP7cVm7tZd1/Vf5E0wBw+GFPLyMOv5S27KDeLfw5uH5lowqRQ4XlYvkpY2x1PMx3TAAsrjzRSxbezqJk7brfjkIrF3GQLlwmM="