language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script: ./travis.sh

env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/jvm'

notifications:  
  email: false
  webhooks:
    urls:
      - secure: "Z+kQRaMkYW0OqDCfZPpx/JwJIqJw1ZkbfKLgr6a4bzwjypTQ/UmrLk1LdugMoQmNMnXmkVUXujLvcXoCUZb+jJ4HxG72VgUybJs8Ee94lhIuj9UT5c41SUX83mI3SIYH6kz1B2El3JUJRpeC7M52XA2g7S5QSUamOPT+pI/PVuM="
      - secure: "f4XdiKFk8AtWlt3oS+RlDgQIHA8w3odyNlSGkSwCgc0HgXFVdFHTnNTJrMB4Acn182Xpbm2Z56HewLP9UsXl4BCoEIUeuQYBMd1bxS/cCTOBrzWParwrtBTxGVoRR+QKiwjWbXkKv4f6TnXunsiZ2NaaQoywEASM+a5YjAKXB6k="
    on_start: always

